package vista;

import Model.Figura;
import Model.Modelo;
import java.awt.Graphics;
import javax.swing.JPanel;

public class PanelDibujo extends JPanel {

  private Modelo modelo;
 
    public PanelDibujo(Modelo modelo) {
        this.modelo = modelo;
        setBackground(java.awt.Color.WHITE);
    }
 
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int escala = 20;
        for (Figura f : modelo.getFiguras()) {
            if (f.tipo.equals("circulo")) {
                g.drawOval(f.x * escala, f.y * escala, f.tamano * escala, f.tamano * escala);
            } else if (f.tipo.equals("rectangulo")) {
                g.drawRect(f.x * escala, f.y * escala, f.tamano * escala, f.tamano * escala);
            }
        }
    }


    /**
     * Creates new form PanelDibujo
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
