package vista;
 
import Model.Modelo;
import java.awt.BorderLayout;
import javax.swing.*;


public class Vista extends JFrame {
    public PanelDibujo panel;
    public JButton btnAgregar, btnLimpiar;
    public JTextField txtX, txtY, txtTamano;
    public JComboBox<String> comboTipo;
 
    public Vista(Modelo modelo) {
        setTitle("Dibujador MVC");
        setSize(700, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
 
        // Panel de dibujo (centro)
        panel = new PanelDibujo(modelo);
        add(panel, BorderLayout.CENTER);
 
        // Formulario de entrada (arriba)
        JPanel formulario = new JPanel();
        formulario.add(new JLabel("Tipo:"));
        comboTipo = new JComboBox<>(new String[]{"circulo", "rectangulo"});
        formulario.add(comboTipo);
 
        formulario.add(new JLabel("X:"));
        txtX = new JTextField(5);
        formulario.add(txtX);
 
        formulario.add(new JLabel("Y:"));
        txtY = new JTextField(5);
        formulario.add(txtY);
 
        formulario.add(new JLabel("Tamaño:"));
        txtTamano = new JTextField(5);
        formulario.add(txtTamano);
 
        add(formulario, BorderLayout.NORTH);
 
        // Botones (abajo)
        JPanel botones = new JPanel();
        btnAgregar = new JButton("Agregar Figura");
        btnLimpiar = new JButton("Limpiar");
        botones.add(btnAgregar);
        botones.add(btnLimpiar);
        add(botones, BorderLayout.SOUTH);
    }

    
    
    /**
     * Creates new form Vista
     */
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}